# Generated by Django 2.0.8 on 2018-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
